
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// ===== BLOCO DE CONFIGURAÇÃO DE API SUPABASE =====
// ⚠️  ARQUIVO GERADO AUTOMATICAMENTE - MAS PODE PRECISAR ATUALIZAR AS CHAVES:
// ⚠️  SUBSTITUA AS CHAVES ABAIXO PELAS SUAS QUANDO NECESSÁRIO:
// 1. SUPABASE_URL: Substitua pela URL do seu projeto Supabase
// 2. SUPABASE_PUBLISHABLE_KEY: Substitua pela chave publicável do seu projeto
// ✅ Encontre suas chaves em: https://supabase.com/dashboard/project/[SEU-PROJETO]/settings/api
const SUPABASE_URL = "https://zwykvxtufkcovqyifhfg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp3eWt2eHR1Zmtjb3ZxeWlmaGZnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1OTkxODAsImV4cCI6MjA2NzE3NTE4MH0.jZos1WwH4o1HqkkAiZsmmYpARATVZDe01E0p4lPOxHE";
// ===== FIM DO BLOCO DE CONFIGURAÇÃO =====

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true
  },
  realtime: {
    params: {
      eventsPerSecond: 10
    }
  }
});
